---
namespace: telekom_mms
name: ansible_collection_icinga
version: 1.1.1
readme: README.md
authors:
  - Christopher Grau <c.grau@telekom.de>
  - Daniel Uhlmann <daniel.uhlmann@telekom.de>
description: >-
  This collection serves as a kind of 'meta collection' for roles and collections, which are used for the
  configuration and administration of individual components of Icinga.
  Additionally, this collection is used to install the Icinga agent and roll out custom checks for every agent.
dependencies:
  telekom_mms.icinga_director: "*"
  telekom_mms.icinga_business_process: "*"
license:
  - GPL-3.0-only
license_file: ""
tags:
  - icinga
  - monitoring
  - agent
  - collection
  - director
  - plugins
repository: https://github.com/telekom-mms/ansible-collection-icinga
documentation: https://github.com/telekom-mms/ansible-collection-icinga
homepage: https://github.com/telekom-mms/ansible-collection-icinga
issues: https://github.com/telekom-mms/ansible-collection-icinga/issues
