---
- name: Create command and service template for check_gitlab_scheduler
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/telekom_mms.icinga_director.icinga:
      url: "{{ icinga_url }}"
      url_username: "{{ icinga_user }}"
      url_password: "{{ icinga_pass }}"
  tasks:
    - name: Create command for check_gitlab_scheduler
      telekom_mms.icinga_director.icinga_command:
        state: present
        object_name: check_gitlab_scheduler
        command: check_gitlab_scheduler.py
        arguments:
          -p:
            required: true
            value: $projectid$
          -s:
            required: true
            value: $schedulerid$
          -t:
            required: true
            value: $token$
          -o:
            required: false
            value: $pending_timeout$
    - name: Create service template for check_gitlab_scheduler
      telekom_mms.icinga_director.icinga_service_template:
        state: present
        object_name: check_gitlab_scheduler
        check_command: "check_gitlab_scheduler"
        check_interval: 5m

# EXAMPLES
## used for service_apply
# - name: "Icinga_service_apply_azure"
#   include_role:
#     name: "telekom_mms.icinga_director.ansible_icinga"
#     tasks_from: "icinga_service_apply"
#   vars:
#     icinga_service_applies:
#     - service_apply_object:
#       - "check_gitlab_scheduler-service_apply"
#       imports: "check_gitlab_scheduler"
#       display_name: "check_gitlab_scheduler_pipelinename"
#       assign_filter: "{{'host.name="gitlab-pipelines"'}}"
#       vars:
#         projectid: "111"
#         schedulerid: "222"
#         token: "{{ gitlab_project_token }}"
