---
- name: Create service template for domon-standard-service and azure REST-API
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/telekom_mms.icinga_director.icinga:
      url: "{{ icinga_url }}"
      url_username: "{{ icinga_user }}"
      url_password: "{{ icinga_pass }}"
    object_name: check_json_azure_restapi
  tasks:
    - name: Create service template for domon-standard-service
      telekom_mms.icinga_director.icinga_service_template:
        state: present
        object_name: domon-standard-service
        max_check_attempts: "3"
        check_period: "24/7"
        check_interval: "2m"
        retry_interval: "1m"
        enable_notifications: true
        enable_active_checks: true
        enable_passive_checks: false
        enable_event_handler: false
        enable_perfdata: true
        volatile: false
        command_endpoint: null
        vars:
          domon_enabled_notifications: ["mail_24/7"]

    - name: Create command Azure REST-API
      telekom_mms.icinga_director.icinga_command:
        state: present
        object_name: azure_restapi
        command: check_json.pl
        arguments:
          --ignoressl:
            set_if: $json_ignoressl$
          -T: $json_contenttype$
          -a:
            required: true
            value: $json_attributes$
          -b:
            required: true
            type: Function
            body: return get_service(macro("$azure_oauth_token_host$"), macro("$azure_oauth_token_service$")).last_check_result.output
          -c:
            required: true
            type: Function
            body: macro("$json_crit$")
          -d: $json_divisor$
          -e: $json_expect$
          -m: $json_metadata$
          -o: $json_outputvars$
          -p: $json_perfvars$
          -t: $json_timeout$
          -u:
            required: true
            value: $json_url$
          -w:
            required: true
            type: Function
            body: macro("$json_warn$")
          -x: $json_xauth$

# EXAMPLES
## used for service_apply
# - name: "Icinga_service_template_azure"
#   include_role:
#     name: "telekom_mms.icinga_director.ansible_icinga"
#     tasks_from: "icinga_service_apply"
#   vars:
#     icinga_service_applies:
#     - service_apply_object:
#       - "azure_restapi-service_apply"
#       imports: "domon-json-azure-restapi"
#       display_name: "azure_restapi"
#       assign_filter: "{{'host.name=\"azure\"'}}"
#       vars:
#         json_url: "https://management.azure.com/subscriptions/xxx"
#         json_attributes: '{properties}->{state}'
#         json_expect: Ready
#         json_ignoressl: true
#         json_outputvars: '{properties}->{state}'
