---
- name: Create service templates for defaults
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/telekom_mms.icinga_director.icinga:
      url: "{{ icinga_url }}"
      url_username: "{{ icinga_user }}"
      url_password: "{{ icinga_pass }}"
  tasks:
    - name: Create service template for domon-standard-service
      telekom_mms.icinga_director.icinga_service_template:
        state: present
        object_name: domon-standard-service
        max_check_attempts: "3"
        check_period: "24/7"
        check_interval: "2m"
        retry_interval: "1m"
        enable_notifications: true
        enable_active_checks: true
        enable_passive_checks: false
        enable_event_handler: false
        enable_perfdata: true
        volatile: false
        command_endpoint: null
        vars:
          domon_enabled_notifications: ["mail_24/7"]

    - name: Create service template for domon-https
      telekom_mms.icinga_director.icinga_service_template:
        state: present
        object_name: domon-https
        imports:
          - domon-standard-service
        check_command: http
        check_interval: 300
        vars:
          http_address: $check_address$
          http_extendedperfdata: false
          http_invertregex: false
          http_sni: true
          http_ssl: true
          http_timeout: 30

    - name: Create service template for domon-https
      telekom_mms.icinga_director.icinga_service_template:
        state: present
        object_name: domon-https-certificate
        imports:
          - domon-https
        check_timeout: 60
