---
- name: Create empty-host template
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/telekom_mms.icinga_director.icinga:
      url: "{{ icinga_url }}"
      url_username: "{{ icinga_user }}"
      url_password: "{{ icinga_pass }}"
      force_basic_auth: "{{ icinga_force_basic_auth | default(omit) }}"
  tasks:
    - name: Create a host in icinga
      telekom_mms.icinga_director.icinga_host_template:
        state: present
        object_name: mms-template-empty-host
        check_command: dummy
